name: workflow

on: push

jobs:
  job1:
    name: Job1
    runs-on: ubuntu-latest
    steps:
    - name: Print Date
      run: echo 'test'
  job2:
    name: Job2
    runs-on: windows-latest
    steps:
    - name: Print Date
      run: echo 'test'
  job3:
    name: Job3
    runs-on: macos-latest
    steps:
    - name: Print Date
      run: echo 'test'
  job4:
    name: Job4
    runs-on: ubuntu-latest
    steps:
    - name: Print Date
      run: echo 'test'